apiVersion: v1
kind: Service
metadata:
  name: that-limit-http-lb
spec:
  type: LoadBalancer
  selector:
    app: that-limit-http
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: that-limit-http
  labels:
    app: that-limit-http
spec:
  replicas: 5
  selector:
    matchLabels:
      app: that-limit-http
  template:
    metadata:
      labels:
        app: that-limit-http
    spec:
      containers:
      - name: that-limit-http
        image: that-limit-http:dev
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
        - name: REDIS_HOST
          value: redis
        - name: REDIS_PORT
          value: "6379"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
